### ISSUE TITLE
highlight code block problem

### ISSUE THREAD

**Issue by ghost** [StartBootstrap/startbootstrap-clean-blog-jekyll#138]
I've cloned the startbootstrap-clean-blog-jekyll repo. I wrote some markdown files at the _post , and  I found that the code block can't be highlighted. How can I solve?

**Comment by oliviervaillancourt** [comment]
I have the same issue, you can see an example of it [here](https://oliviervaillancourt.com/2017/12/12/Freedome-discount-using-serverless.html) (scroll down to step 4).

I also included in `_config.yml' the following
```
highlighter: rouge
```

Any help would be greatly appreciated.  

Great theme

**Comment by clintgibler** [comment]
I just started using Jekyll today and have been playing around with this template, so this probably a horribly hacky way to do it, but it seems to work.

## Background

Somewhere in the Jekyll docs they mention that each theme is responsible for importing CSS that handles syntax highlighting. 

If you look in the SCSS directory for this theme, you can see that it does not appear to do that:
https://github.com/BlackrockDigital/startbootstrap-clean-blog-jekyll/tree/master/assets/vendor/startbootstrap-clean-blog/scss

If we look in the default theme, minima, we can see that it does it in [_syntax-highlighting.scss](https://github.com/jekyll/minima/blob/master/_sass/minima/_syntax-highlighting.scss)

## Solution

### 1. Find this theme's location on your computer
First, find the gem directory for this theme on your computer by running `bundle show jekyll-theme-clean-blog` in the root of your blog directory. 

For me on macOS using rbenv, it was `/Users/<username>/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jekyll-theme-clean-blog-4.0.0.1`.

### 2. Import a syntax highlighting file
Now edit `assets/vendor/startbootstrap-clean-blog/scss/clean-blog.scss` in that directory. It'll look like [this](https://github.com/BlackrockDigital/startbootstrap-clean-blog-jekyll/blob/master/assets/vendor/startbootstrap-clean-blog/scss/clean-blog.scss).

Add the following line to the end of `clean-blog.scss`:

~~~
@import "syntax-highlighting.scss"
~~~

### 3. Add the syntax highlighting file itself

Then copy the contents of the file [_syntax-highlighting.scss](https://github.com/jekyll/minima/blob/master/_sass/minima/_syntax-highlighting.scss) from the minima repo into a file called `_syntax-highlighting.scss` in the same directory as `clean-blog.scss`, modified above.

Also, comment out the `vertical-rhythm` line in `_syntax-highlighting.scss`, like so:

~~~
  /* @extend %vertical-rhythm; */
~~~

### 4. Profit!

Syntax highlighting in posts like the following should now work:

~~~
{% highlight ruby %}
def print_hi(name)
  puts "Hi, #{name}"
end
print_hi('Tom')
#=> prints 'Hi, Tom' to STDOUT.
{% endhighlight %}
~~~

~~~
```ruby
def print_hi(name)
  puts "Hi, #{name}"
end
print_hi('Tom')
#=> prints 'Hi, Tom' to STDOUT.
```
~~~

Note: you'll probably need to restart the `jekyll` server before the changes will be recognized.

## Next steps

If someone who is more familiar with Jekyll wants to make a PR for this change or describe a more idiomatic way to do it, that'd be much appreciated.

**Comment by sahilpatel14** [comment]
Any update on this issue? @clintgibler, it's a neat hack. Thank you for that. It has solved my issue for the time being but we still need a permanent fix.

**Comment by clintgibler** [comment]
@sahilpatel14 Unfortunately the author of this theme seems permanently AFK. Note the number of directly mergeable PRs that are still open (like [this](https://github.com/BlackrockDigital/startbootstrap-clean-blog-jekyll/pull/137/files) one).

I'd say patch your own locally, unless someone is willing to maintain and update a fork?

**Comment by sahilpatel14** [comment]
I have customised my blog with this theme and it looks [dope](https://www.ninthsemester.com/). I don't want this awesome project to go dormant. Lets hope the author returns soon.

**Comment by fuhrmanator** [comment]
I had this problem. I think syntax highlighting was happening (I could see in Chrome that there were `<span />` tags around keywords, etc. in my code, but there was no CSS for the styles to "see" the formatting. 

My solution was to add a [syntax.css](https://gist.github.com/demisx/8408522) into the style sheets that get pulled in. 

As for a PR, I don't know how to proceed. I'm new to Jekyll and don't really understand well enough how Clean Blog's supposed to be forked to start one's own blog. When I tried it with GitHub pages I had trouble with missing files. Everything works locally (jekyll) but I don't want to commit some 1500+ files (esp. CSS in fontawesome) to a GitHub repo (which is what Git is saying is necessary.)

**Comment by sangwoo-joh** [comment]
I had this too.
I solved using the way @fuhrmanator has mentioned.
You can choose any of syntax highlight css from [predefined css](https://github.com/iwootten/jekyll-syntax) or make your own.
Just add `syntax.css` file and include it in your `head.html` or other places. I will just work.

**Comment by renwuli** [comment]
@sahilpatel14  Hi, do you face the problem that post date cannot be 2019? If I create a post dated in 2019, then the webpage does not show that post.
