### ISSUE TITLE
images on markdown files

### ISSUE THREAD

**Issue by Ivonneg** [StartBootstrap/startbootstrap-clean-blog-jekyll#182]
I am having a lot of trouble displaying my images on this theme.

I am not using unsplash, I have the images saved in a folder called _img. 

Here is the original code: 
<img class="img-fluid" src="https://source.unsplash.com/Mn9Fa_wQH-M/800x450" alt="Demo Image">

Mine code:
<img class="img-fluid" src="img/bg-about.jpg" alt="Demo Image">
There is only a small image icon shown. 

Has anyone else had this issue? I have done a lot of intense google searching, but the format for markdown I found doesn't work either. 

Any advice would be great!!

**Comment by NoobCam** [comment]
> 
> 
> I am having a lot of trouble displaying my images on this theme.
> 
> I am not using unsplash, I have the images saved in a folder called _img.
> 
> Here is the original code:
> ![Demo Image](https://camo.githubusercontent.com/e124599b65aee7bac1cb67cb6af0bb9c8a714a14/68747470733a2f2f736f757263652e756e73706c6173682e636f6d2f4d6e3946615f7751482d4d2f38303078343530)
> 
> Mine code:
> ![Demo Image](img/bg-about.jpg)
> There is only a small image icon shown.
> 
> Has anyone else had this issue? I have done a lot of intense google searching, but the format for markdown I found doesn't work either.
> 
> Any advice would be great!!

please post your code, the link you posted is broken.

**Comment by Ivonneg** [comment]
> > I am having a lot of trouble displaying my images on this theme.
> > I am not using unsplash, I have the images saved in a folder called _img.
> > Here is the original code:
> > ![Demo Image](https://camo.githubusercontent.com/e124599b65aee7bac1cb67cb6af0bb9c8a714a14/68747470733a2f2f736f757263652e756e73706c6173682e636f6d2f4d6e3946615f7751482d4d2f38303078343530)
> > Mine code:
> > ![Demo Image](img/bg-about.jpg)
> > There is only a small image icon shown.
> > Has anyone else had this issue? I have done a lot of intense google searching, but the format for markdown I found doesn't work either.
> > Any advice would be great!!
> 
> please post your code, the link you posted is broken.

My code 

`---
layout: post
title:  "WindyCityRails Advertisement"
subtitle: "Creating conference advertisements."
background: '/img/posts/post-three.jpg'
---

<p>Never in all their history have men been able truly to conceive of the world as one: a single sphere, a globe, having the qualities of a globe, a round earth in which all the directions eventually meet, in which there is no center because every point, or none, is center — an equal earth which all men occupy as equals. The airman's earth, if free men make it, will be truly round: a globe in practice, not in theory.</p>

<p>Science cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science.</p>

<p>What was most significant about the lunar voyage was not that man set foot on the Moon but that they set eye on the earth.</p>

<p>A Chinese tale tells of some men sent to harm a young girl who, upon seeing her beauty, become her protectors rather than her violators. That's how I felt seeing the Earth for the first time. I could not help but love and cherish her.</p>

<p>For those who have seen the Earth from space, and for the hundreds and perhaps thousands more who will, the experience most certainly changes your perspective. The things that we share in our world are far more valuable than those which divide us.</p>

<h2 class="section-heading">The First Design: What was Wrong</h2>

<p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>

<p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>

<blockquote class="blockquote">The dreams of yesterday are the hopes of today and the reality of tomorrow. Science has not yet mastered prophecy. We predict too much for the next year and yet far too little for the next ten.</blockquote>

<p>Spaceflights cannot be stopped. This is not the work of any one man or even a group of men. It is a historical process which mankind is carrying out in accordance with the natural laws of human development.</p>

<h2 class="section-heading">The Second Design: What was Better</h2>

<p>As we got further and further away, it [the Earth] diminished in size. Finally it shrank to the size of a marble, the most beautiful you can imagine. That beautiful, warm, living object looked so fragile, so delicate, that if you touched it with a finger it would crumble and fall apart. Seeing this has to change a man.</p>

<img class="img-fluid" src="img/posts/speaker_ad.png" alt="newAd">
<span class="caption text-muted">New Ad Design</span>

<h2 class="section-heading">Reflection</h2>

<p>Space, the final frontier. These are the voyages of the Starship Enterprise. Its five-year mission: to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no man has gone before.</p>

<p>As I stand out here in the wonders of the unknown at Hadley, I sort of realize there’s a fundamental truth to our nature, Man must explore, and this is exploration at its greatest.</p>
`

**Comment by Ivonneg** [comment]
This time I didn't quote it, so hopefully you can see it all now.

---
layout: post
title:  "WindyCityRails Advertisement"
subtitle: "Creating conference advertisements."
background: '/img/posts/post-three.jpg'
---

<p>Never in all their history have men been able truly to conceive of the world as one: a single sphere, a globe, having the qualities of a globe, a round earth in which all the directions eventually meet, in which there is no center because every point, or none, is center — an equal earth which all men occupy as equals. The airman's earth, if free men make it, will be truly round: a globe in practice, not in theory.</p>

<p>Science cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science.</p>

<p>What was most significant about the lunar voyage was not that man set foot on the Moon but that they set eye on the earth.</p>

<p>A Chinese tale tells of some men sent to harm a young girl who, upon seeing her beauty, become her protectors rather than her violators. That's how I felt seeing the Earth for the first time. I could not help but love and cherish her.</p>

<p>For those who have seen the Earth from space, and for the hundreds and perhaps thousands more who will, the experience most certainly changes your perspective. The things that we share in our world are far more valuable than those which divide us.</p>

<h2 class="section-heading">The First Design: What was Wrong</h2>

<p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>

<p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>

<blockquote class="blockquote">The dreams of yesterday are the hopes of today and the reality of tomorrow. Science has not yet mastered prophecy. We predict too much for the next year and yet far too little for the next ten.</blockquote>

<p>Spaceflights cannot be stopped. This is not the work of any one man or even a group of men. It is a historical process which mankind is carrying out in accordance with the natural laws of human development.</p>

<h2 class="section-heading">The Second Design: What was Better</h2>

<p>As we got further and further away, it [the Earth] diminished in size. Finally it shrank to the size of a marble, the most beautiful you can imagine. That beautiful, warm, living object looked so fragile, so delicate, that if you touched it with a finger it would crumble and fall apart. Seeing this has to change a man.</p>

<img class="img-fluid" src="img/posts/speaker_ad.png" alt="newAd">
<span class="caption text-muted">New Ad Design</span>

<h2 class="section-heading">Reflection</h2>

<p>Space, the final frontier. These are the voyages of the Starship Enterprise. Its five-year mission: to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no man has gone before.</p>

<p>As I stand out here in the wonders of the unknown at Hadley, I sort of realize there’s a fundamental truth to our nature, Man must explore, and this is exploration at its greatest.</p>

**Comment by Ivonneg** [comment]
```
---
layout: post
title:  "WindyCityRails Advertisement"
subtitle: "Creating conference advertisements."
background: '/img/posts/post-three.jpg'
---

<p>Never in all their history have men been able truly to conceive of the world as one: a single sphere, a globe, having the qualities of a globe, a round earth in which all the directions eventually meet, in which there is no center because every point, or none, is center — an equal earth which all men occupy as equals. The airman's earth, if free men make it, will be truly round: a globe in practice, not in theory.</p>

<p>Science cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science.</p>

<p>What was most significant about the lunar voyage was not that man set foot on the Moon but that they set eye on the earth.</p>

<p>A Chinese tale tells of some men sent to harm a young girl who, upon seeing her beauty, become her protectors rather than her violators. That's how I felt seeing the Earth for the first time. I could not help but love and cherish her.</p>

<p>For those who have seen the Earth from space, and for the hundreds and perhaps thousands more who will, the experience most certainly changes your perspective. The things that we share in our world are far more valuable than those which divide us.</p>

<h2 class="section-heading">The First Design: What was Wrong</h2>

<p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>

<p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>

<blockquote class="blockquote">The dreams of yesterday are the hopes of today and the reality of tomorrow. Science has not yet mastered prophecy. We predict too much for the next year and yet far too little for the next ten.</blockquote>

<p>Spaceflights cannot be stopped. This is not the work of any one man or even a group of men. It is a historical process which mankind is carrying out in accordance with the natural laws of human development.</p>

<h2 class="section-heading">The Second Design: What was Better</h2>

<p>As we got further and further away, it [the Earth] diminished in size. Finally it shrank to the size of a marble, the most beautiful you can imagine. That beautiful, warm, living object looked so fragile, so delicate, that if you touched it with a finger it would crumble and fall apart. Seeing this has to change a man.</p>

<img class="img-fluid" src="img/posts/speaker_ad.png" alt="newAd">
<span class="caption text-muted">New Ad Design</span>

<h2 class="section-heading">Reflection</h2>

<p>Space, the final frontier. These are the voyages of the Starship Enterprise. Its five-year mission: to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no man has gone before.</p>

<p>As I stand out here in the wonders of the unknown at Hadley, I sort of realize there’s a fundamental truth to our nature, Man must explore, and this is exploration at its greatest.</p>
```

**Comment by NoobCam** [comment]
Looks like your looking for the image in the wrong place
```
background: '/img/posts/post-three.jpg'
```
You mention you made a folder called _img

**Comment by davidtmiller** [comment]
Also make sure your image paths are correct! Thanks @NoobCam for helping out on this one.
