### ISSUE TITLE
Could not add multiple blog pages

### ISSUE THREAD

**Issue by gokcedilek** [StartBootstrap/startbootstrap-clean-blog-jekyll#194]
Hello,

I would like to create multiple blog post categories, each showing on a separate page. For this, in my ```gokcedilek.github.io``` repository that I forked from [https://github.com/BlackrockDigital/startbootstrap-clean-blog-jekyll](url), I created two separate folders named "blog1" and "blog2", added a "_posts" directory for each, and removed the default "_posts" directory. However, I do not know how to proceed with this. How could I manage to display multiple blog pages on my website?

Thank you very much!
Gokce Dilek

**Comment by narko** [comment]
You need to make sure you use the jekyll-paginate-v2 gem. I faced problems with this issue as well. You can find a configuration example here: https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#page-configuration
