### ISSUE TITLE
Support Git pages

### ISSUE THREAD

**Issue by BeatrizCarvalho** [StartBootstrap/startbootstrap-clean-blog-jekyll#208]
Hello, I am trying to use the theme in git pages, but the formatting is not working.
What should I do?

**Comment by NishanthVAnand** [comment]
I am facing the same problem as well. Did you find a solution to it?

**Comment by matheusaraujo** [comment]
I've used the plugin https://github.com/benbalter/jekyll-remote-theme and it worked.
