### ISSUE TITLE
Support for Jekyll 4.0

### ISSUE THREAD

**Issue by Goles** [StartBootstrap/startbootstrap-clean-blog-jekyll#211]
I think this theme has a hard dependency on Jekyll 3.6, is supporting 4.0 in the roadmap?

```
Bundler could not find compatible versions for gem "jekyll":
  In snapshot (Gemfile.lock):
    jekyll (= 4.0.0)

  In Gemfile:
    jekyll (~> 4.0.0)

    jekyll-theme-clean-blog was resolved to 4.0.1, which depends on
      jekyll (~> 3.6)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by mattcarey** [comment]
I am getting this error as well. Is there a work around?

**Comment by VascoRibeiroPereira** [comment]
you can install and run jekyll 3.6 (dont forget to change the gem "jekyll", "~> 3.5" in the Gemfile). This worked for me.

**Comment by thejimnicholson** [comment]
By updating the Gemfile and .gemspec, I was able to use this theme with Jekyll 4.0. I've submitted a PR for the changes I made: https://github.com/BlackrockDigital/startbootstrap-clean-blog-jekyll/pull/223

**Comment by djcaesar9114** [comment]
Indeed, the support for Jekyll 4.0 would be great...

**Comment by davidtmiller** [comment]
Done, thanks all!
