### ISSUE TITLE
Can not set year as 2019 for new posters 

### ISSUE THREAD

**Issue by shiqi1994** [StartBootstrap/startbootstrap-clean-blog-jekyll#212]
Sorry to bother but it confused me when I am going to write a new poster. It do not show in the preview poster list if I set year as 2019. Any suggestions? Thanks!

**Comment by renwuli** [comment]
@shiqi1994  yes, I have encountered this problem as well, did you fix it? Pls let me know.

**Comment by davidtmiller** [comment]
Keep in mind if you show a date that has not yet come the post will not publish.
