### ISSUE TITLE
markdown support

### ISSUE THREAD

**Issue by mikyone** [StartBootstrap/startbootstrap-clean-blog-jekyll#221]
I try to use clean blog with md file. It seems it's not supported ? Can you tell how I can go over this limitation.
Cheers

**Comment by avishreekh** [comment]
If you are trying to create a post using markdown, just create a file name-of-the-post.md in the _posts directory. Add the necessary front matter (layout etc). Also, ensure that the name of the post starts with the date (for example, 2020-03-16-post.md) (use a past date). 

Take a look at this post that I added for better understanding:
[https://raw.githubusercontent.com/avishreekh/avishreekh.github.io/master/_posts/2020-03-16-cross-entropy-method-rl.md](https://raw.githubusercontent.com/avishreekh/avishreekh.github.io/master/_posts/2020-03-16-cross-entropy-method-rl.md)

Hope this helps!
