### ISSUE TITLE
Anyone give me a quick walkthrough on where I can customize things?

### ISSUE THREAD

**Issue by KingJacM** [StartBootstrap/startbootstrap-clean-blog-jekyll#232]
For example, font, where can I customize it? Sorry for the noob question.

**Comment by codewithpav** [comment]
You can overide in: assets/vendor/startbootstrap-clean-blog/scss/_bootstrap-overrides.scss

I hope this helps to point you in the right direction.

**Comment by KingJacM** [comment]
> You can overide in: assets/vendor/startbootstrap-clean-blog/scss/_bootstrap-overrides.scss
> 
> I hope this helps to point you in the right direction.

Yes! And I can insert a <style> tag in the layouts HTML to overwrite in css!
