### ISSUE TITLE
adding a profile picture (not GitHub avatar) in the center of navbar for about page

### ISSUE THREAD

**Issue by cetienn01** [StartBootstrap/startbootstrap-clean-blog-jekyll#235]
I am trying to add a profile image in the middle of the nav bar in the about page but i cannot seem to figure out how.
The only option I cam across was to use the `gem jekyll-avatar`. 
So i was able to load the "avatar" (my profile picture from github) by using this method: 
`{% avatar cetienn01 %}` <br>
However, I want to use a different picture, from different source, let's say one that is on a `folder on my computer`, or maybe one from a `url`. Any suggestions on how to do this?

**Comment by davidtmiller** [comment]
You could go into the layout components and add an image into the navbar manually. That would probably be the easiest way to do that. Hopefully this helps!
